# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wenyi Zhao
email: zhaowenyi94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a daily landing of Wenyi Zhao, a passionate person who like reading traveling and coding.
  NEWS: I will exchange to KTH(Royal Institute of Technology) in Sweden for one year after Aug.2016, and I will record my life there through this blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhaowenyi94.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  zhaowenyi94
weibo_username: @赵闻一

# Build settings
markdown: kramdown
