# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wenyi Zhao
email: zhaowenyi94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Funny guy who like coding and traveling.

baseurl: "www.zhaowenyi.me" # the subpath of your site, e.g. /blog
url: "https://zhaowenyi94.github.io" # the base hostname & protocol for your site
twitter_username: DavidZhao
github_username:  zhaowenyi94
weibo_username: 赵闻一
linkedin_username: Wenyi Zhao

# Build settings
markdown: kramdown
